### ISSUE TITLE
Restructured text confusion

### ISSUE THREAD

**Issue by iainhouston** [timonwong/OmniMarkupPreviewer#72]
This is pretty well what I was aiming for: 

![screenshot from https://www.tele3.cz/jbar/rest/rest.html](https://cloud.githubusercontent.com/assets/537596/6901077/cea43560-d702-11e4-88ef-2f24c589d862.png)  

using this markup: 
![source](https://cloud.githubusercontent.com/assets/537596/6901128/2384cdba-d703-11e4-8285-aa828e1bbdeb.png)  

but omniviewer got a bit confused at the third bullet: 
![readme_rst _users_iainhouston_documents_web_pyprojects_iainhouston_com_mysite](https://cloud.githubusercontent.com/assets/537596/6901161/610cd682-d703-11e4-84d6-81bdd4a67df1.png)

Notice that Omniviewer put in *Italics* and a **Block Quotes** margin contrary to my expectations.

**Comment by timonwong** [comment]
Hi, this is what GitHub style does, if you are not satisfy with this, you can do customization to CSS file, step by step:

1. Copy `github.css` from `{PackagesDir}/OmniMarkupPreviewer/public/github.css` to `{PackagesDir}/User/OmniMarkupPreviewer/public` (the user folder should already exist).
2. Open `github.css` in that *user* folder you copied before, find the following contents:
```css
.markdown-body dl dt {
    font-size: 14px;
    font-style: italic;
    font-weight: bold;
    margin: 15px 0 5px;
    padding: 0;
}
```

Replace to:

```css
.markdown-body dl dt {
    font-size: 14px;
    font-style: normal;
    font-weight: normal;
    margin: 15px 0 5px;
    padding: 0;
}
```
3. Reload the page.
